### ISSUE TITLE
tag a non-zero version

### ISSUE THREAD

**Issue by StefanKarpinski** [johnmyleswhite/SmoothingKernels.jl#4]
This is one of the only packages in METADATA without versions > `v"0.0.0"` that has other packages depending on it. Using zero versions has been unrecommended for some time and will not be supported in Pkg3, so this package should either be tagged or dropped as a dependency for @joshday's [`AverageShiftedHistograms`](https://github.com/joshday/AverageShiftedHistograms.jl) package.

**Comment by joshday** [comment]
SmoothingKernels was dropped as a dependency for AverageShiftedHistograms maybe a year ago?

**Comment by StefanKarpinski** [comment]
I just noticed that. Sorry for the noise.
